# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_basic_where = {
    'am looking for the': 8,
 'am trying to find': 8,
 'can i find the': 8,
 'can i get to': 8,
 'can you give me': 8,
 'can you help me': 16,
 'can you inform me': 8,
 'can you point me': 8,
 'can you tell me': 32,
 'could give me some': 16,
 'do we do when': 8,
 'give me directions to': 8,
 'give me some directions': 16,
 'go to find the': 8,
 'help me find the': 8,
 'help me locate the': 8,
 'how can i get': 8,
 'how do i': 8,
 'how do i find': 8,
 'how is': 8,
 'how many': 8,
 'how much': 8,
 'how much is': 8,
 'how much money': 8,
 'how much money is': 8,
 'how to get to': 8,
 'i am looking for': 8,
 'i am trying to': 8,
 'i can find the': 8,
 'i get to the': 8,
 'i need to find': 8,
 'i would like it': 8,
 "i'd like it if": 8,
 'if you could give': 16,
 'inform me where i': 8,
 'is there a': 8,
 'is there an': 8,
 'it if you could': 16,
 'like it if you': 16,
 'me directions to the': 8,
 'me how to get': 8,
 'me some directions to': 16,
 'me the way to': 8,
 'me where i can': 8,
 'me where to go': 8,
 'need to find the': 8,
 'point me towards the': 8,
 'some directions to the': 16,
 'tell me how to': 8,
 'tell me the way': 8,
 'tell me where the': 8,
 'tell me where to': 8,
 'the way to the': 8,
 'to get to the': 8,
 'to go to find': 8,
 'trying to find the': 8,
 'what do we do': 8,
 'what does': 8,
 'what is': 8,
 'what is a': 8,
 'what is an': 8,
 'what is the': 8,
 'where are': 8,
 'where can i find': 8,
 'where i can find': 8,
 'where is': 8,
 'where is the': 8,
 'where to go to': 8,
 'would like it if': 8,
 'you could give me': 16,
 'you give me directions': 8,
 'you help me find': 8,
 'you help me locate': 8,
 'you inform me where': 8,
 'you point me towards': 8,
 'you tell me how': 8,
 'you tell me the': 8,
 'you tell me where': 16
}
