# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_basic_what = {
    'am looking for the': 2,
 'am trying to find': 2,
 'can i find the': 2,
 'can i get to': 2,
 'can you give me': 2,
 'can you help me': 4,
 'can you inform me': 2,
 'can you point me': 2,
 'can you tell me': 8,
 'could give me some': 4,
 'do we do when': 2,
 'give me directions to': 2,
 'give me some directions': 4,
 'go to find the': 2,
 'help me find the': 2,
 'help me locate the': 2,
 'how can i get': 2,
 'how do i': 2,
 'how do i find': 2,
 'how is': 2,
 'how many': 2,
 'how much': 2,
 'how much is': 2,
 'how much money': 2,
 'how much money is': 2,
 'how to get to': 2,
 'i am looking for': 2,
 'i am trying to': 2,
 'i can find the': 2,
 'i get to the': 2,
 'i need to find': 2,
 'i would like it': 2,
 "i'd like it if": 2,
 'if you could give': 4,
 'inform me where i': 2,
 'is there a': 2,
 'is there an': 2,
 'it if you could': 4,
 'like it if you': 4,
 'me directions to the': 2,
 'me how to get': 2,
 'me some directions to': 4,
 'me the way to': 2,
 'me where i can': 2,
 'me where to go': 2,
 'need to find the': 2,
 'point me towards the': 2,
 'some directions to the': 4,
 'tell me how to': 2,
 'tell me the way': 2,
 'tell me where the': 2,
 'tell me where to': 2,
 'the way to the': 2,
 'to get to the': 2,
 'to go to find': 2,
 'trying to find the': 2,
 'what do we do': 2,
 'what does': 2,
 'what is': 2,
 'what is a': 2,
 'what is an': 2,
 'what is the': 2,
 'where are': 2,
 'where can i find': 2,
 'where i can find': 2,
 'where is': 2,
 'where is the': 2,
 'where to go to': 2,
 'would like it if': 2,
 'you could give me': 4,
 'you give me directions': 2,
 'you help me find': 2,
 'you help me locate': 2,
 'you inform me where': 2,
 'you point me towards': 2,
 'you tell me how': 2,
 'you tell me the': 2,
 'you tell me where': 4
}
