# coding: utf-8

"""
    Collibra Catalog classification API

    <p>The Catalog API offers functionality related to the catalog product.<br/> It is mainly focused on facilitating the ingestion of information into Catalog. The API enables users to more easily connect Catalog to sources that are not necessarily natively supported in the product. </p>  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import collibra_data_classification
from collibra_data_classification.models.named_resource_reference_impl import NamedResourceReferenceImpl  # noqa: E501
from collibra_data_classification.rest import ApiException

class TestNamedResourceReferenceImpl(unittest.TestCase):
    """NamedResourceReferenceImpl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NamedResourceReferenceImpl
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = collibra_data_classification.models.named_resource_reference_impl.NamedResourceReferenceImpl()  # noqa: E501
        if include_optional :
            return NamedResourceReferenceImpl(
                id = '2b7f3a1a-4e50-4077-96f0-a58a395c860d', 
                resource_type = 'Community', 
                name = '0'
            )
        else :
            return NamedResourceReferenceImpl(
                id = '2b7f3a1a-4e50-4077-96f0-a58a395c860d',
                resource_type = 'Community',
        )

    def testNamedResourceReferenceImpl(self):
        """Test NamedResourceReferenceImpl"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
