"""
    MetaFab API

     Complete MetaFab API references and guides can be found at: https://trymetafab.com  # noqa: E501

    The version of the OpenAPI document: 1.2
    Contact: metafabproject@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import metafab_python
from metafab_python.api.exchanges_api import ExchangesApi  # noqa: E501


class TestExchangesApi(unittest.TestCase):
    """ExchangesApi unit test stubs"""

    def setUp(self):
        self.api = ExchangesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_exchange(self):
        """Test case for create_exchange

        Create exchange  # noqa: E501
        """
        pass

    def test_get_exchange_offer(self):
        """Test case for get_exchange_offer

        Get exchange offer  # noqa: E501
        """
        pass

    def test_get_exchange_offers(self):
        """Test case for get_exchange_offers

        Get exchange offers  # noqa: E501
        """
        pass

    def test_get_exchanges(self):
        """Test case for get_exchanges

        Get exchanges  # noqa: E501
        """
        pass

    def test_remove_exchange_offer(self):
        """Test case for remove_exchange_offer

        Remove exchange offer  # noqa: E501
        """
        pass

    def test_set_exchange_offer(self):
        """Test case for set_exchange_offer

        Set exchange offer  # noqa: E501
        """
        pass

    def test_use_exchange_offer(self):
        """Test case for use_exchange_offer

        Use exchange offer  # noqa: E501
        """
        pass

    def test_withdraw_from_exchange(self):
        """Test case for withdraw_from_exchange

        Withdraw from exchange  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
