
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-11T11:50:38-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ea933ee1718da918dfc6067e7c5f1a60f3c310a",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
