class OutputMode: ...

class RsDio:
    def setXmlFile(self, filename: str, debug: bool=False) -> bool: ...
    def setOutputMode(self, dio: int, mode: OutputMode) -> int: ...
    def digitalRead(self, dio: int, pin: int) -> int: ...
    def digitalWrite(self, dio: int, pin: int, state: bool) -> int: ...
    def getLastError(self) -> str: ...
    def version(self) -> str: ...
