
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-15T04:42:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8472b55516f3ead809726b24ffd71d49a5dee4e",
 "version": "1.17.1.post0.dev470"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
