
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-13T19:37:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "07867e11faf38d71b7534e60fca219b6d7c59dfa",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
