# -*- coding: utf-8 -*-

# -*- coding: UTF-8 -*-

d_what_who = {
    'am looking for the': 7,
 'am trying to find': 7,
 'can i find the': 7,
 'can i get to': 7,
 'can you give me': 7,
 'can you help me': 14,
 'can you inform me': 7,
 'can you point me': 7,
 'can you tell me': 28,
 'could give me some': 14,
 'do we do when': 7,
 'give me directions to': 7,
 'give me some directions': 14,
 'go to find the': 7,
 'help me find the': 7,
 'help me locate the': 7,
 'how can i get': 7,
 'how do i': 7,
 'how do i find': 7,
 'how is': 7,
 'how many': 7,
 'how much': 7,
 'how much is': 7,
 'how much money': 7,
 'how much money is': 7,
 'how to get to': 7,
 'i am looking for': 7,
 'i am trying to': 7,
 'i can find the': 7,
 'i get to the': 7,
 'i need to find': 7,
 'i would like it': 7,
 "i'd like it if": 7,
 'if you could give': 14,
 'inform me where i': 7,
 'is there a': 7,
 'is there an': 7,
 'it if you could': 14,
 'like it if you': 14,
 'me directions to the': 7,
 'me how to get': 7,
 'me some directions to': 14,
 'me the way to': 7,
 'me where i can': 7,
 'me where to go': 7,
 'need to find the': 7,
 'point me towards the': 7,
 'some directions to the': 14,
 'tell me how to': 7,
 'tell me the way': 7,
 'tell me where the': 7,
 'tell me where to': 7,
 'the way to the': 7,
 'to get to the': 7,
 'to go to find': 7,
 'trying to find the': 7,
 'what do we do': 7,
 'what does': 7,
 'what is': 7,
 'what is a': 7,
 'what is an': 7,
 'what is the': 7,
 'where are': 7,
 'where can i find': 7,
 'where i can find': 7,
 'where is': 7,
 'where is the': 7,
 'where to go to': 7,
 'would like it if': 7,
 'you could give me': 14,
 'you give me directions': 7,
 'you help me find': 7,
 'you help me locate': 7,
 'you inform me where': 7,
 'you point me towards': 7,
 'you tell me how': 7,
 'you tell me the': 7,
 'you tell me where': 14
}
