"""
    Cisco SD-WAN vManage API

    The vManage API exposes the functionality of operations maintaining devices and the overlay network  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: vmanage@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.monitoring_health_devices_api import MonitoringHealthDevicesApi  # noqa: E501


class TestMonitoringHealthDevicesApi(unittest.TestCase):
    """MonitoringHealthDevicesApi unit test stubs"""

    def setUp(self):
        self.api = MonitoringHealthDevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_devices_health(self):
        """Test case for get_devices_health

        """
        pass

    def test_get_devices_health_overview(self):
        """Test case for get_devices_health_overview

        """
        pass


if __name__ == '__main__':
    unittest.main()
