# Generated by Django 3.0.14 on 2021-10-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0009_indicationofpolicynotificationsdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicationofpolicynotifications',
            name='indication_details',
        ),
        migrations.AlterField(
            model_name='indicationofpolicynotificationsdetails',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Undefined'), (1, 'Sent Successfully'), (2, 'Not Sent No Permission For Notifications'), (3, 'Not Sent Notification For Obsolete Event'), (4, 'Not Sent Due To Error'), (5, 'Not Passed Validation')], db_column='Status', default=0),
        ),
    ]
