
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-12T10:38:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd3c47e262ff163b3fa029fb1f1130f804236ffd",
 "version": "1.97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
