
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-15T00:44:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "31363ecb1e29b96e9048ff250f5a562951fb1d11",
 "version": "1.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
