# coding: utf-8

"""
    Collibra Import API

    <p>The Import API is an efficient way to load large volumes of data into the Collibra Data Governance Center. The API can automatically differentiate between creating and updating data.</p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import collibra_importer
from collibra_importer.models.import_summary import ImportSummary  # noqa: E501
from collibra_importer.rest import ApiException

class TestImportSummary(unittest.TestCase):
    """ImportSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImportSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = collibra_importer.models.import_summary.ImportSummary()  # noqa: E501
        if include_optional :
            return ImportSummary(
                resource_types = [
                    collibra_importer.models.resource_type_summary.ResourceTypeSummary(
                        resource_type = 'COMMUNITY', 
                        counters = collibra_importer.models.import_counters.ImportCounters(
                            added = 56, 
                            removed = 56, 
                            updated = 56, ), 
                        subcategories = [
                            collibra_importer.models.subcategory_summary.SubcategorySummary(
                                category = collibra_importer.models.category_reference.CategoryReference(
                                    id = '0', 
                                    name = '0', ), )
                            ], )
                    ], 
                errors_count = 56, 
                import_job_state = 'COMPLETED'
            )
        else :
            return ImportSummary(
        )

    def testImportSummary(self):
        """Test ImportSummary"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
