# coding: utf-8

"""
    Collibra Import API

    <p>The Import API is an efficient way to load large volumes of data into the Collibra Data Governance Center. The API can automatically differentiate between creating and updating data.</p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import collibra_importer
from collibra_importer.models.synchronization_csv_in_job_request import SynchronizationCsvInJobRequest  # noqa: E501
from collibra_importer.rest import ApiException

class TestSynchronizationCsvInJobRequest(unittest.TestCase):
    """SynchronizationCsvInJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SynchronizationCsvInJobRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = collibra_importer.models.synchronization_csv_in_job_request.SynchronizationCsvInJobRequest()  # noqa: E501
        if include_optional :
            return SynchronizationCsvInJobRequest(
                send_notification = True, 
                batch_size = 1, 
                simulation = True, 
                save_result = True, 
                synchronization_id = '0', 
                file_id = '0', 
                file = bytes(b'blah'), 
                file_name = '0', 
                delete_file = True, 
                continue_on_error = True, 
                separator = '0', 
                quote = '0', 
                escape = '0', 
                strict_quotes = True, 
                ignore_leading_whitespace = True, 
                header_row = True, 
                template = '0'
            )
        else :
            return SynchronizationCsvInJobRequest(
                synchronization_id = '0',
                separator = '0',
                quote = '0',
                escape = '0',
                template = '0',
        )

    def testSynchronizationCsvInJobRequest(self):
        """Test SynchronizationCsvInJobRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
