# coding: utf-8

"""
    Collibra Import API

    <p>The Import API is an efficient way to load large volumes of data into the Collibra Data Governance Center. The API can automatically differentiate between creating and updating data.</p>  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import collibra_importer
from collibra_importer.models.attribute_value import AttributeValue  # noqa: E501
from collibra_importer.rest import ApiException

class TestAttributeValue(unittest.TestCase):
    """AttributeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AttributeValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = collibra_importer.models.attribute_value.AttributeValue()  # noqa: E501
        if include_optional :
            return AttributeValue(
                value = '0', 
                values = [
                    '0'
                    ]
            )
        else :
            return AttributeValue(
        )

    def testAttributeValue(self):
        """Test AttributeValue"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
