# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.3'
git_version = '00ee0d91e8664760fd937b476d698ba6fae17f49'
