# Generated by Django 3.0.3 on 2021-06-18 07:45

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuree', '0012_policyrenewaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNotification',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('family', models.OneToOneField(db_column='FamilyID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='family_notification', serialize=False, to='insuree.Family')),
                ('approval_of_notification', models.BooleanField(db_column='ApprovalOfSMS', default=False)),
                ('language_of_notification', models.CharField(db_column='LanguageOfSMS', default='en', max_length=5)),
            ],
            options={
                'db_table': 'tblFamilySMS',
                'managed': False,
            },
        ),
    ]
