# Generated by Django 3.0.3 on 2021-06-20 17:57

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_auto_20201021_0811'),
        ('policy_notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationOfPolicyNotifications',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('policy', models.OneToOneField(db_column='PolicyID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='indication_of_notifications', serialize=False, to='policy.Policy')),
                ('activation_of_policy', models.DateField(db_column='NotificationOnActivationSent', null=True)),
                ('starting_of_policy', models.DateField(db_column='NotificationOnEffectiveSent', null=True)),
                ('need_for_renewal', models.DateField(db_column='NotificationBeforeExpirySent', null=True)),
                ('expiration_of_policy', models.DateField(db_column='NotificationOnExpirationSent', null=True)),
                ('reminder_after_expiration', models.DateField(db_column='NotificationAfterExpirationSent', null=True)),
                ('renewal_of_policy', models.DateField(db_column='NotificationOnRenewalSent', null=True)),
            ],
            options={
                'db_table': 'tblIndicationOfPolicyNotifications',
            },
        ),
    ]
