# Generated by Django 3.0.14 on 2021-10-17 17:43

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0008_existing_policies_indication'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationOfPolicyNotificationsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('notification_type', models.CharField(db_column='notification_type', max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'Undefined'), (1, 'Sent Successfully'), (2, 'Not Sent No Permission For Notifications'), (3, 'Not Sent Notification For Obsolete Event'), (4, 'Not Sent Due To Error Error')], db_column='Status', default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('indication_of_notification', models.ForeignKey(db_column='indicationID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='policy_notification.IndicationOfPolicyNotifications')),
            ],
            options={
                'db_table': 'tblIndicationOfPolicyNotificationsDetails',
            },
        ),
    ]
