# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cells.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cell_pb2 as cell__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x65lls.proto\x1a\ncell.proto\"^\n\x05\x43\x65lls\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.Cells.ItemsEntry\x1a\x33\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Cell:\x02\x38\x01\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cells_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _CELLS_ITEMSENTRY._options = None
  _CELLS_ITEMSENTRY._serialized_options = b'8\001'
  _CELLS._serialized_start=27
  _CELLS._serialized_end=121
  _CELLS_ITEMSENTRY._serialized_start=70
  _CELLS_ITEMSENTRY._serialized_end=121
# @@protoc_insertion_point(module_scope)
