# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computation_binding.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import computation_variable_binding_pb2 as computation__variable__binding__pb2
from . import record_auditinfo_pb2 as record__auditinfo__pb2
from . import execution_details_pb2 as execution__details__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63omputation_binding.proto\x1a\"computation_variable_binding.proto\x1a\x16record_auditinfo.proto\x1a\x17\x65xecution_details.proto\"\x92\x02\n\x12\x43omputationBinding\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rcomputationId\x18\x02 \x01(\t\x12:\n\x15inputVariableBindings\x18\x03 \x03(\x0b\x32\x1b.ComputationVariableBinding\x12\x1a\n\x12outputColumnNumber\x18\x04 \x01(\r\x12\x18\n\x10requireAllInputs\x18\x05 \x01(\x08\x12\x0f\n\x07isValid\x18\x06 \x01(\x08\x12+\n\x10\x65xecutionDetails\x18\x07 \x01(\x0b\x32\x11.ExecutionDetails\x12)\n\x0frecordAuditInfo\x18\x63 \x01(\x0b\x32\x10.RecordAuditInfoB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'computation_binding_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _COMPUTATIONBINDING._serialized_start=115
  _COMPUTATIONBINDING._serialized_end=389
# @@protoc_insertion_point(module_scope)
