# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_variable_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65num_variable_type.proto*w\n\x10\x45numVariableType\x12\x18\n\x14VARIABLETYPE_UNKNOWN\x10\x00\x12\x16\n\x12VARIABLETYPE_VALUE\x10\x01\x12\x16\n\x12VARIABLETYPE_ARRAY\x10\x02\x12\x19\n\x15VARIABLETYPE_NULLABLE\x10\x03\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_variable_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _ENUMVARIABLETYPE._serialized_start=28
  _ENUMVARIABLETYPE._serialized_end=147
# @@protoc_insertion_point(module_scope)
