# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_worksheet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65num_worksheet.proto*\x86\x01\n\rEnumWorksheet\x12\x15\n\x11WORKSHEET_UNKNOWN\x10\x00\x12\x1c\n\x18WORKSHEET_FIFTEEN_MINUTE\x10\x01\x12\x12\n\x0eWORKSHEET_HOUR\x10\x02\x12\x17\n\x13WORKSHEET_FOUR_HOUR\x10\x03\x12\x13\n\x0fWORKSHEET_DAILY\x10\x04\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_worksheet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _ENUMWORKSHEET._serialized_start=25
  _ENUMWORKSHEET._serialized_end=159
# @@protoc_insertion_point(module_scope)
