# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_limit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65num_limit.proto*\xa7\x01\n\tEnumLimit\x12\x11\n\rLIMIT_UNKNOWN\x10\x00\x12\x13\n\x0fLIMIT_HIGHALARM\x10\x01\x12\x12\n\x0eLIMIT_HIGHNEAR\x10\x02\x12\x11\n\rLIMIT_LOWNEAR\x10\x03\x12\x12\n\x0eLIMIT_LOWALARM\x10\x04\x12\x14\n\x10LIMIT_REGULATORY\x10\x05\x12\x11\n\rLIMIT_WARNING\x10\x06\x12\x0e\n\nLIMIT_GOAL\x10\x07\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_limit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _ENUMLIMIT._serialized_start=21
  _ENUMLIMIT._serialized_end=188
# @@protoc_insertion_point(module_scope)
