# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution_details.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import enum_time_unit_pb2 as enum__time__unit__pb2
from . import enum_output_placement_pb2 as enum__output__placement__pb2
from . import enum_wims_week_definition_pb2 as enum__wims__week__definition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xecution_details.proto\x1a\x14\x65num_time_unit.proto\x1a\x1b\x65num_output_placement.proto\x1a\x1f\x65num_wims_week_definition.proto\"\xcf\x01\n\x10\x45xecutionDetails\x12-\n\x0foutputPlacement\x18\x01 \x01(\x0e\x32\x14.EnumOutputPlacement\x12\x1a\n\x12numberOfExecutions\x18\x02 \x01(\r\x12!\n\ntimePeriod\x18\x03 \x01(\x0e\x32\r.EnumTimeUnit\x12\x18\n\x10timeWindowOffset\x18\x04 \x01(\r\x12\x33\n\x12wimsWeekDefinition\x18\x05 \x01(\x0e\x32\x17.EnumWimsWeekDefinitionB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_details_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _EXECUTIONDETAILS._serialized_start=112
  _EXECUTIONDETAILS._serialized_end=319
# @@protoc_insertion_point(module_scope)
