# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jsonTicksDateTime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17jsonTicksDateTime.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8d\x01\n\x11JsonTicksDateTime\x12\x34\n\x0cjsonDateTime\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x12-\n\x05ticks\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt64ValueH\x00\x42\x13\n\x11jsonTicksDateTimeB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jsonTicksDateTime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _JSONTICKSDATETIME._serialized_start=60
  _JSONTICKSDATETIME._serialized_end=201
# @@protoc_insertion_point(module_scope)
