# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: row.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cell_pb2 as cell__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trow.proto\x1a\ncell.proto\".\n\x03Row\x12\x11\n\trowNumber\x18\x01 \x01(\r\x12\x14\n\x05\x63\x65lls\x18\x03 \x03(\x0b\x32\x05.Cell\"[\n\x04Rows\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.Rows.ItemsEntry\x1a\x32\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x13\n\x05value\x18\x02 \x01(\x0b\x32\x04.Row:\x02\x38\x01\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'row_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _ROWS_ITEMSENTRY._options = None
  _ROWS_ITEMSENTRY._serialized_options = b'8\001'
  _ROW._serialized_start=25
  _ROW._serialized_end=71
  _ROWS._serialized_start=73
  _ROWS._serialized_end=164
  _ROWS_ITEMSENTRY._serialized_start=114
  _ROWS_ITEMSENTRY._serialized_end=164
# @@protoc_insertion_point(module_scope)
