# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenant_product_offering.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtenant_product_offering.proto\x1a\x1egoogle/protobuf/wrappers.proto\"w\n\x15TenantProductOffering\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x19\n\x11productOfferingId\x18\x02 \x01(\t\x12\x31\n\x0bpropertyBag\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"?\n\x16TenantProductOfferings\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.TenantProductOfferingB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenant_product_offering_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _TENANTPRODUCTOFFERING._serialized_start=65
  _TENANTPRODUCTOFFERING._serialized_end=184
  _TENANTPRODUCTOFFERINGS._serialized_start=186
  _TENANTPRODUCTOFFERINGS._serialized_end=249
# @@protoc_insertion_point(module_scope)
