
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-10T09:51:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "14e82f475c8f364b226554064d3b978d8d2fca96",
 "version": "0.1.40.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
