
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-09T21:03:26-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "97b9bba3ed4f3eb9c7bdd664a3a71cdbe8bc967a",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
