# Generated by Django 3.2.16 on 2022-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SChSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SChSetup',
                'verbose_name_plural': 'SChSetups',
                'default_permissions': ('can_administer', 'add', 'change', 'delete', 'list'),
            },
        ),
    ]
