
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-03T11:45:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "eadc6e33eddbdcd7fe2c5a184dc70c934b89e5f3",
 "version": "2.8.8.dev20221110"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
