# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20026_engine_types_engine_type import InlineResponse20026EngineTypesEngineType  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20026EngineTypesEngineType(unittest.TestCase):
    """InlineResponse20026EngineTypesEngineType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026EngineTypesEngineType(self):
        """Test InlineResponse20026EngineTypesEngineType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20026_engine_types_engine_type.InlineResponse20026EngineTypesEngineType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
