
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-07T23:48:30+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "afa8f7486ab4ea1869499d9e1d4b434f1ad0efe3",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
