
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-14T05:48:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fdba8c8183786622a364c82d2da31a3bce90aaa",
 "version": "1.17.1.post0.dev461"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
