
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-10T13:20:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "89b9b9253ea04667a95eca64a66253d33f4e3276",
 "version": "0.3.10.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
