
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-14T10:47:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "57a20c00fba07e0905af50febd2bdaae8ec3cd63",
 "version": "0.2.0.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
