
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-11T13:30:29-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "95d5fdc15dc014696c36f3317ceb216fbaf04acf",
 "version": "7.3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
