
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-10T13:07:30-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "9074c1587cb0d7c2ad6dc38cece2de1b209166ca",
 "version": "2.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
