
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-12T10:56:03+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "43cc3acd187d35a938ffcb1af29f5d675b6d3ca3",
 "version": "v0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
