# Generated by Django 3.2 on 2022-11-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0006_remove_text_lang'),
        ('apis_ampel', '0003_delete_ampelgeneric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampeltemp',
            name='temp_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ampel', to='apis_metainfo.tempentityclass'),
        ),
    ]
