
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-15T13:26:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e05294a4cc2ae1918e2ab875e30d969ec41ac6f3",
 "version": "2794"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
