
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-14T22:10:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1932d558239f6d7b571cc0a64c6d96313b085df",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
