# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracdap/config/runtime.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tracdap.config import platform_pb2 as tracdap_dot_config_dot_platform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctracdap/config/runtime.proto\x12\x0etracdap.config\x1a\x1dtracdap/config/platform.proto\"\x93\x04\n\rRuntimeConfig\x12\x39\n\x06\x63onfig\x18\x01 \x03(\x0b\x32).tracdap.config.RuntimeConfig.ConfigEntry\x12;\n\x07storage\x18\x02 \x03(\x0b\x32*.tracdap.config.RuntimeConfig.StorageEntry\x12\x45\n\x0crepositories\x18\x03 \x03(\x0b\x32/.tracdap.config.RuntimeConfig.RepositoriesEntry\x12\x38\n\x0fstorageSettings\x18\x04 \x01(\x0b\x32\x1f.tracdap.config.StorageSettings\x12\x34\n\rsparkSettings\x18\x05 \x01(\x0b\x32\x1d.tracdap.config.SparkSettings\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aM\n\x0cStorageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.tracdap.config.StorageConfig:\x02\x38\x01\x1aU\n\x11RepositoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .tracdap.config.RepositoryConfig:\x02\x38\x01\"@\n\x0fStorageSettings\x12\x16\n\x0e\x64\x65\x66\x61ultStorage\x18\x01 \x01(\t\x12\x15\n\rdefaultFormat\x18\x02 \x01(\t\"\x85\x01\n\rSparkSettings\x12\x41\n\nsparkProps\x18\x01 \x03(\x0b\x32-.tracdap.config.SparkSettings.SparkPropsEntry\x1a\x31\n\x0fSparkPropsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1c\n\x18org.finos.tracdap.configP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracdap.config.runtime_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.finos.tracdap.configP\001'
  _RUNTIMECONFIG_CONFIGENTRY._options = None
  _RUNTIMECONFIG_CONFIGENTRY._serialized_options = b'8\001'
  _RUNTIMECONFIG_STORAGEENTRY._options = None
  _RUNTIMECONFIG_STORAGEENTRY._serialized_options = b'8\001'
  _RUNTIMECONFIG_REPOSITORIESENTRY._options = None
  _RUNTIMECONFIG_REPOSITORIESENTRY._serialized_options = b'8\001'
  _SPARKSETTINGS_SPARKPROPSENTRY._options = None
  _SPARKSETTINGS_SPARKPROPSENTRY._serialized_options = b'8\001'
  _RUNTIMECONFIG._serialized_start=80
  _RUNTIMECONFIG._serialized_end=611
  _RUNTIMECONFIG_CONFIGENTRY._serialized_start=400
  _RUNTIMECONFIG_CONFIGENTRY._serialized_end=445
  _RUNTIMECONFIG_STORAGEENTRY._serialized_start=447
  _RUNTIMECONFIG_STORAGEENTRY._serialized_end=524
  _RUNTIMECONFIG_REPOSITORIESENTRY._serialized_start=526
  _RUNTIMECONFIG_REPOSITORIESENTRY._serialized_end=611
  _STORAGESETTINGS._serialized_start=613
  _STORAGESETTINGS._serialized_end=677
  _SPARKSETTINGS._serialized_start=680
  _SPARKSETTINGS._serialized_end=813
  _SPARKSETTINGS_SPARKPROPSENTRY._serialized_start=764
  _SPARKSETTINGS_SPARKPROPSENTRY._serialized_end=813
# @@protoc_insertion_point(module_scope)
