
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-12T02:50:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "eace7f689b061121656f295d4b14393c08c004be",
 "version": "2.8.9.dev20221113"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
