
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-13T02:41:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c81b9467b43bb14e77956729d10f2aef4d69deec",
 "version": "1.1.dev2246"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
