
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-13T09:59:53+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d75da8983618ee3b178be1af999a297fc6e68535",
 "version": "4.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
