
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-15T16:17:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "40daf6359f0efa1d724649e06e4ee6a187b5fe1d",
 "version": "0.2.0.post0.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
