JOB_TYPE_FORECAST_SERIES = "job_forecast"
JOB_TYPE_DETECT_ANOMALIES_FOR_SERIES = "job_anomaly_detect"

JOB_TYPE_IDS = {
    JOB_TYPE_FORECAST_SERIES: 1,
    JOB_TYPE_DETECT_ANOMALIES_FOR_SERIES: 2
}

JOB_TYPE_NAMES = {
    1: JOB_TYPE_FORECAST_SERIES,
    2: JOB_TYPE_DETECT_ANOMALIES_FOR_SERIES
}

JOB_TYPES = [
    JOB_TYPE_FORECAST_SERIES,
    JOB_TYPE_DETECT_ANOMALIES_FOR_SERIES
]

JOB_STATUS_NONE = None
JOB_STATUS_OPEN = 1
JOB_STATUS_PENDING = 2
JOB_STATUS_DONE = 3
JOB_STATUS_FAILED = 4
