# Generated by Django 3.2.3 on 2022-09-11 07:35

from django.db import migrations, models
import dvadmin_ak_sk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkSkManage',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('access_key', models.CharField(default=dvadmin_ak_sk.models.ConsumerSecretKeyGenerator('access_key'), max_length=64, unique=True, verbose_name='access_key')),
                ('access_secret', models.CharField(default=dvadmin_ak_sk.models.ConsumerSecretKeyGenerator('access_secret'), max_length=64, unique=True, verbose_name='access_secret')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, help_text='状态', verbose_name='状态')),
            ],
            options={
                'verbose_name': 'ak/sk管理',
                'verbose_name_plural': 'ak/sk管理',
                'ordering': ('create_datetime',),
            },
        ),
    ]
