# Generated by Django 3.2.3 on 2022-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_ak_sk', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akskmanage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
    ]
