
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-10T14:18:21+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3dce1698955c2a339160ae5b053afd8672f1348",
 "version": "4.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
