
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-15T11:08:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa94ebbe2777655ec20bafab540e6c3550c23738",
 "version": "0.7.1.post.dev800"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
