
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-14T23:53:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6347ad2763162d93da7aa13ad4d61592a43a4b97",
 "version": "1.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
