
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-16T03:00:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8a22defcb27f664d2bee0bd13696159c3b3302a",
 "version": "0.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
