
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-14T23:17:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f46432d11c6e3155830e120c2f92eb5ce40b9b5",
 "version": "1.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
