
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-15T11:53:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "56327d81660fe8ac067e4943f4a764b84ae63348",
 "version": "2792"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
