
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-10T10:52:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c8e73427ebc8fb035be420cd606ecd7ef9b0420",
 "version": "v1.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
