# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%tensorflow/core/protobuf/status.proto\x12\ntensorflow\"\x0f\n\rDerivedStatus\"\xa0\x01\n\x11StackTracePayload\x12>\n\x0cstack_frames\x18\x01 \x03(\x0b\x32(.tensorflow.StackTracePayload.StackFrame\x1aK\n\nStackFrame\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0bline_number\x18\x02 \x01(\x05\x12\x15\n\rfunction_name\x18\x03 \x01(\tBWZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_protob\x06proto3')



_DERIVEDSTATUS = DESCRIPTOR.message_types_by_name['DerivedStatus']
_STACKTRACEPAYLOAD = DESCRIPTOR.message_types_by_name['StackTracePayload']
_STACKTRACEPAYLOAD_STACKFRAME = _STACKTRACEPAYLOAD.nested_types_by_name['StackFrame']
DerivedStatus = _reflection.GeneratedProtocolMessageType('DerivedStatus', (_message.Message,), {
  'DESCRIPTOR' : _DERIVEDSTATUS,
  '__module__' : 'tensorflow.core.protobuf.status_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.DerivedStatus)
  })
_sym_db.RegisterMessage(DerivedStatus)

StackTracePayload = _reflection.GeneratedProtocolMessageType('StackTracePayload', (_message.Message,), {

  'StackFrame' : _reflection.GeneratedProtocolMessageType('StackFrame', (_message.Message,), {
    'DESCRIPTOR' : _STACKTRACEPAYLOAD_STACKFRAME,
    '__module__' : 'tensorflow.core.protobuf.status_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.StackTracePayload.StackFrame)
    })
  ,
  'DESCRIPTOR' : _STACKTRACEPAYLOAD,
  '__module__' : 'tensorflow.core.protobuf.status_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.StackTracePayload)
  })
_sym_db.RegisterMessage(StackTracePayload)
_sym_db.RegisterMessage(StackTracePayload.StackFrame)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto'
  _DERIVEDSTATUS._serialized_start=53
  _DERIVEDSTATUS._serialized_end=68
  _STACKTRACEPAYLOAD._serialized_start=71
  _STACKTRACEPAYLOAD._serialized_end=231
  _STACKTRACEPAYLOAD_STACKFRAME._serialized_start=156
  _STACKTRACEPAYLOAD_STACKFRAME._serialized_end=231
# @@protoc_insertion_point(module_scope)
