__title__ = 'crypto_payments'
__description__ = 'Receive cryptocurrency payment, generate hd cryptocurrency wallet addresses and verifying payment made to an address.'
__url__ = 'https://github.com/ydaniels/HD-Merchant-wallet'
__version__ = '1.1.2'
__author__ = 'halt'
__author_email__ = 'yomidall@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020'