#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2204-86-gd5221d19"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2204
#define NETGEN_VERSION_TWEAK 86
#define NETGEN_VERSION_HASH "gd5221d19"
#endif // NETGEN_VERSION_HPP_INCLUDED
