
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-11T16:46:48+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c7b5e99719a8f3d397985da12f35d6c1435d76c",
 "version": "1.95.5.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
